01 woman function
K-chan41/mokumoku pull request #4
Opened 2023-08-27 09:59 UTC by K-chan41

### 選択した課題
サービス登録者数の内、男性60%に対して、女性は40%。一方で、サービス内のもくもく会に参加した人の比率は、男性90%：女性10%と大きな差が出ています。もっと女性が使いやすいようなサービス設計にする必要があるのではないか？

### ローカルテストの結果
[![Image from Gyazo](https://i.gyazo.com/36d05460bc6ed8da9f401b120a0ec02a.png)](https://gyazo.com/36d05460bc6ed8da9f401b120a0ec02a)
ご指導ご鞭撻のほどよろしくおねがいします。

### Gitがうまく使えていない件
Git操作に不慣れでわけがわからない状態になってしまったので、初期のブランチから新たにブランチを切り直し、実装をやり直しました。ローカルテストもクリアさせ、changed fileの数もまともになりました。
gitのcommitとかの取り消しを何度もやってわけがわからなくなってしまったので、勉強し直しておきます。

2023-08-27 23:39 UTC, busitora requested changes

2023-08-27 23:39 UTC, busitora commented on app/controllers/events/attendances_controller.rb
> +      end
9~11行目までロジックを持ちすぎているので、model に処理を移し、model spec を追加してください!

2023-08-27 23:39 UTC, busitora commented on app/views/events/show.html.erb
> +                  <% if (current_user.woman? && @event.only_woman?) || !@event.only_woman? %>
条件式が複雑なので、こちらもmodelメソッドに移譲するとベターです。

2023-08-28 12:02 UTC, K-chan41 commented on app/controllers/events/attendances_controller.rb
> +      end
9~11行目までをevent_attendanceモデルに移動させました。

2023-08-28 12:02 UTC, K-chan41 commented on app/views/events/show.html.erb
> +                  <% if (current_user.woman? && @event.only_woman?) || !@event.only_woman? %>
条件式をuserモデルに移動させました。

2023-08-28 12:39 UTC, busitora approved these changes
LGTM!

2023-08-29 02:28 UTC, merged